### ISSUE TITLE
Error when using galleryOnly and uploading to database

### ISSUE THREAD

**Issue by arcelluceno11** [Drjacky/ImagePicker#77]
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{7df89b7 8444:com.capstone.sharity/u0a85} (pid=8444, uid=10085) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

**Comment by Drjacky** [comment]
What version you're using?

**Comment by arcelluceno11** [comment]
2.3.20

**Comment by arcelluceno11** [comment]
Device is Xiaomi Poco F4 and Api Version 32

On sample app its' working but I haven't tested it on uploading the uri to a database.

**Comment by arcelluceno11** [comment]
I currently writing the project on MVVM approach. This is the snippet.

MutableLiveData<Uri> paymentProof = new MutableLiveData<>();
Firebase.getStorage()
                    .getReferenceFromUrl("gs://sh*******ot.com/Pu***/")
                    .child(paymentProof.getValue().getLastPathSegment())
                    .putFile(paymentProof.getValue());
                    
Displaying the received uri in an ImageView both cameraOnly and galleryOnly works, but when I upload the uri to the database only the cameraOnly seems to be working.

**Comment by Drjacky** [comment]
Can you try adding this code snippet before using the URI:
```kotlin
requireActivity().contentResolver.takePersistableUriPermission(
                uri,
                Intent.FLAG_GRANT_READ_URI_PERMISSION
            )
            // Do something else with the URI. Upload or insert to DB
```

And please let me know if it solved the issue or not

**Comment by arcelluceno11** [comment]
I'm getting a new error

No persistable permission grants found for UID 10085 and Uri content://com.android.providers.media.documents/document/image:95

**Comment by arcelluceno11** [comment]
Update: 

I revert the code to its default. galleryOnly() only works if I add .crop() to it same with .bothCameraGallery(). If not, the error persist and I think that's the problem. The problem only persist using gallery.

I hope in the later updates this problem will be fix. Thanks for helping me by the way.

**Comment by Drjacky** [comment]
> I'm getting a new error
> 
> No persistable permission grants found for UID 10085 and Uri content://com.android.providers.media.documents/document/image:95

My bad, that `takePersistableUriPermission` is only for `ACTION_OPEN_DOCUMENT` and other actions in the Storage Access Framework, not for `ACTION_GET_CONTENT`

**Comment by Drjacky** [comment]
Please create a sample app that reproduce the issue. @arcelluceno11

**Comment by Drjacky** [comment]
It's not related to the library but I'll improve the sample app.
You just need to add:
```kotlin
mGalleryUri?.let { galleryUri ->
                        contentResolver.takePersistableUriPermission(
                            galleryUri, Intent.FLAG_GRANT_READ_URI_PERMISSION
                        )
                    }
```

https://developer.android.com/training/data-storage/shared/photopicker#persist-media-file-access

_____

Please re-open the issue if it didn't help in your case.

**Comment by Drjacky** [comment]
# In case you don't use Crop option, you need just need to add:
```kotlin
mGalleryUri?.let { galleryUri ->
                        contentResolver.takePersistableUriPermission(
                            galleryUri, Intent.FLAG_GRANT_READ_URI_PERMISSION
                        )
                    }
```

https://developer.android.com/training/data-storage/shared/photopicker#persist-media-file-access
________
I'll change `ACTION_GET_CONTENT` to `ACTION_OPEN_DOCUMENT` on the next update.  
[And if I could find a way to have both worlds(having crop and let developer use or not use `takePersistableUriPermission`, I'll update again.]

**Comment by Drjacky** [comment]
Fixed on [2.3.21](https://github.com/Drjacky/ImagePicker/releases/tag/2.3.21).

**Comment by Drjacky** [comment]
I improved the readme and reverted back from `ACTION_OPEN_DOCUMENT ` to `ACTION_GET_CONTENT ` on [2.3.22](https://github.com/Drjacky/ImagePicker/releases/tag/2.3.22).

**Comment by ASKabanets** [comment]
Still facing with this issue on version 2.3.22 when picking from "Pictures" folder on local device even with added permission.
`requireActivity().contentResolver.takePersistableUriPermission(imageUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)`
Picked file uri = content://com.android.providers.media.documents/document/image%3A25

ImagePicker.with(requireActivity())
                    .provider(ImageProvider.BOTH)
                    .setOutputFormat(Bitmap.CompressFormat.PNG)
                    .createIntentFromDialog {
                        if (it.resolveActivity(requireContext().packageManager) != null) {
                            imagePickerLauncher.launch(it)
                        } else {
                            requireActivity().snackBar(R.string.image_pick_failed)
                        }
                    }

Upd: if not add this line
`requireActivity().contentResolver.takePersistableUriPermission(imageUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)`
file picking works.
